esphome:
  name: dekacontroller

external_components:
  source:
     type: local
     path: ./components
#  source:
#    type: git
#    url: https://github.com/grob6000/dekacontroller-esphome
#    username: !secret github_username
#    password: !secret github_token
  
esp8266:
  board: esp12e

# Enable logging
logger:
  baud_rate: 0
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption1

ota:
  password: "da9a71b09eaa2394deb3dfe42091980b"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: true
  domain: ".localdomain"
  fast_connect: true

uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

dekacontroller:
  id: dc1
  uart_id: uart_bus
  gps:
    name: Dekacontroller GPS
  sync:
    name: Dekacontroller Sync
  run:
    name: Dekacontroller Running
  track:
    name: Dekacontroller Track
  drift:
    name: Dekacontroller Drift
  zerom0:
    name: Dekacontroller Zero M0
  zerom00:
    name: Dekacontroller Zero M00
  zeroh0:
    name: Dekacontroller Zero H0
  zeroh00:
    name: Dekacontroller Zero H00
  runin:
    name: Dekacontroller Run Input
  runout:
    name: Dekacontroller Run Output
  timezone:
    name: Dekacontroller Timezone