esphome:
  name: dekacontroller
  includes:
   - dekacontroller.h
  
esp8266:
  board: esp12e

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "DC29vOGSun1fQ5tpuexxdKNGh83ApPeagLOr4hjwRkY="

ota:
  password: "da9a71b09eaa2394deb3dfe42091980b"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: true
  domain: ".localdomain"
  fast_connect: true

uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

sensor:
  - platform: custom
    lambda: |-
      auto s = new DekaController(id(uart_bus));
      App.register_component(s);
      return {s->gps_state, s->sync_state, s->run_state, s->drift};
    sensors:
     - name: deka_gps_state
     - name: deka_sync_state
     - name: deka_run_state
     - name: deka_drift
       unit_of_measurement: s
      